# Generated by Django 3.2.4 on 2022-07-02 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader', models.CharField(max_length=25)),
                ('counterparty', models.CharField(max_length=256)),
                ('instrumentName', models.CharField(max_length=256)),
                ('tradeDateTime', models.DateTimeField(verbose_name=datetime.datetime)),
            ],
        ),
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buySellIndicator', models.CharField(max_length=5)),
            ],
        ),
    ]
